export const CLEAN_CHARACTER_DETAIL = "CLEAN_CHARACTER_DETAIL";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const DELETE_FAVORITE = "DELETE_FAVORITE";
export const FILTER = "FILTER";
export const ORDER = "ORDER";